### ISSUE TITLE
Trouble with UnZipping .pak files for Hunt Showdown

### ISSUE THREAD

**Issue by sethlangel** [Markemp/Cryengine-Converter#63] opened 2021-07-17 12:29 UTC
I'm not sure I'm not doing this correctly but I'm positive I am. I am using 7zip to extract the .pak files but it comes with an error saying "cannot open file as archive". Since Hunt is a newer game with Crytek are the .pak files encrypted? If they are is there a way to get past it?

**Comment by vmxeo** [comment] 2021-07-17 14:10
I believe there are game specific tools for extracting the .pak files; cryengine-converter definitely isn't it. You may need to hunt (pun intended) for a Hunt Showdown modding group for guidance. This issue tracking forum is specific to the tool used for asset conversion once the data file is uncompressed.

**Comment by sethlangel** [comment] 2021-07-18 04:16
Hey! Thank you for pointing me in the right direction. I now have the files decrypted and converted to .dae files. However if I put the .dae files into blender the file imports with no errors but ther is not model in blender. Any idea whats going on? Thanks!

**Comment by Markemp** [comment] 2021-07-20 20:24
Which model is not working?

**Comment by sethlangel** [comment] 2021-07-21 21:53
I couldn’t get any of the .dae files to show in blende but the main ones I’m looking for are the butcher model and his weapon

**Comment by Markemp** [comment] 2021-07-21 21:57
Closing this issue as it's a duplicate of #70

**Closed by Markemp** 2021-07-21 21:57 UTC

**Comment by bltsbb** [comment] 2025-06-03 18:33
> 嘿！感谢您为我指明正确的方向。现在，我已解密文件并将其转换为 .dae 文件。但是，如果我将.dae文件放入 blender 中，文件导入时没有错误，但在 blender 中不是模型。知道发生了什么吗？谢谢！

hey，how to unpack .pak,Can you provide a website?
